# PVC => PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  这个指的是 mysql 有哪些volume
  name: webook-mysql-claim
spec:
#  可以随便取名字
  storageClassName: suibian
  accessModes:
#    一个POD读写
    - ReadWriteOnce
#    多个POD读，一个POD写
#    - ReadOnlyMany
#    多个POD读写
#    - ReadWriteMany
  resources:
    requests:
#      1GB
      storage: 1Gi

